User registration
JavaHaterNLovers/ConferenceManagementSystem pull request #10
Opened 2017-04-04 16:18 UTC by mihaiToader

Am facut Registration. Am adaugat un buton in login.

2017-04-04 16:38 UTC, raress96 requested changes

2017-04-04 16:38 UTC, decebaldecebal commented on src/main/java/controller/RegisterCtrl.java
> +    private Boolean notEmptyFields(){
Nu trebuie sa faci asta, pentru asta exista anotarile de validari pe entitate.In exceptia aruncata (ValidationException), o sa ai toate stringurile cu erori si doar trebuie sa le afisezi.Ai putea sa si faci o functie in helper care ia un obiect ValidationException ca si parametru si afiseaza toate erorile, una pe linie, intr-un error alert.

2017-04-04 16:39 UTC, mihaiToader commented on src/main/java/controller/RegisterCtrl.java
> +    private Boolean notEmptyFields(){
Ok, modific imediat

2017-04-04 19:15 UTC, raress96 requested changes

2017-04-04 19:15 UTC, decebaldecebal commented on src/main/java/controller/RegisterCtrl.java
> +    private Boolean validatePasswords(){
Si pentru length exista anotari de validare, @Length daca nu ma insel.

2017-04-04 19:15 UTC, decebaldecebal commented on src/main/java/controller/RegisterCtrl.java
> +    private Boolean notEmptyFields(){
Vad ca tot nu ai sters asta :))

2017-04-04 19:15 UTC, decebaldecebal commented on src/main/java/controller/RegisterCtrl.java
> +    private String getErrorMessage(ConstraintViolationException constraintViolationException){
Muta asta ii UIUtils ca si statica.

2017-04-04 20:28 UTC, mihaiToader commented on src/main/java/controller/RegisterCtrl.java
> +    private Boolean validatePasswords(){
Nu pot folosi @length pentru ca parola e memorata codificata. Am modificat emailul sa fie unique.

2017-04-05 06:00 UTC, raress96 requested changes

2017-04-05 06:00 UTC, decebaldecebal commented on src/main/java/controller/RegisterCtrl.java
> +    private Boolean validatePasswords(){
Ok.Muta si asta in UserService si totul e ok :)

2017-04-05 10:56 UTC, raress96 approved these changes

2017-04-05 10:56 UTC, merged